"""
Django settings for miniproject1 project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(5690gn29=01j@50cqz$go#ktw3^ya3!vq8br=0ytge(j8cl+w"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 127.0.0.1이 아닌 다른 IP로 서버를 열 때 입력
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '172.20.10.5']
#'127.0.0.1', 'localhost', '172.20.10.4'
#'127.0.0.1', 'localhost','172.20.10.2'
#'127.0.0.1', 'localhost','192.168.70.224'
#'127.0.0.1', 'localhost', '192.168.17.56'

# Application definition

# 프로젝트에서 추가한 APP입력
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'bootstrap4',
    "test1",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "miniproject1.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "miniproject1.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#연동할 데이터베이스 정보 입력
DATABASES = {
    "default": {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : 'asgard',
        'USER' : 'root',
        'PASSWORD' : 'Asgard',
        'HOST' : 'localhost',
        'PORT' : '3306',
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",#strict mode 설정 추가
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

# USE_TZ의 default=True -> False
# USE_TZ = True : Django 내부적으로 시간대를 인식하는 날자 및 시간 가용
# USE_TZ = False : Local Time을 사용
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# static 관련 수정사항
STATIC_URL = '/static/'  #'static/'
import os
STATICFILES_DIR = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
