# Generated by Django 4.1.3 on 2022-12-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_led_tblheater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Led',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
