# Generated by Django 4.1.3 on 2022-12-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_sensor_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('led_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'led',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblHeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('d_heat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_heater',
                'managed': False,
            },
        ),
    ]
